# Energy Score Tool Configuration
# This file contains all configurable parameters for the energy scoring and comparison system

# =============================================================================
# SCORING SYSTEM CONFIGURATION
# =============================================================================
scoring:
  # Star rating system (1-5 stars, 5 = best)
  star_rating:
    min_stars: 1.0
    max_stars: 5.0
    default_score: 3.0  # Neutral score when values are identical
  
  # Metric weights for composite scoring (must sum to 1.0)
  metric_weights:
    energy_efficiency: 0.4
    co2_efficiency: 0.3
    performance: 0.2
    speed: 0.1
    cost_effectiveness: 0.0  # Can be enabled by setting weight > 0
  
  # Validation thresholds
  validation:
    max_coefficient_of_variation: 0.15  # Reject measurements with CV > 15%
    default_coefficient_of_variation: 0.03  # Default CV for mock data
    variation_range: 0.05  # Random variation factor for realistic testing

# =============================================================================
# MODEL PROFILES CONFIGURATION
# =============================================================================
model_profiles:
  # Default fallback values for unknown models
  defaults:
    energy_per_1k_wh: 5.0
    co2_per_1k_g: 2.5
    samples_per_second: 50
    duration_seconds: 20.0
    size_mb: 100
    architecture: "Unknown"
  
  # Text Generation Models
  text_generation:
    "distilgpt2":
      energy_per_1k_wh: 2.1
      co2_per_1k_g: 1.0
      samples_per_second: 120
      duration_seconds: 8.3
      size_mb: 82
      architecture: "GPT-2"
    
    "gpt2":
      energy_per_1k_wh: 3.5
      co2_per_1k_g: 1.7
      samples_per_second: 80
      duration_seconds: 12.5
      size_mb: 548
      architecture: "GPT-2"
    
    "gpt2-medium":
      energy_per_1k_wh: 6.2
      co2_per_1k_g: 3.1
      samples_per_second: 45
      duration_seconds: 22.2
      size_mb: 1240
      architecture: "GPT-2"
    
    "gpt2-large":
      energy_per_1k_wh: 12.5
      co2_per_1k_g: 6.2
      samples_per_second: 25
      duration_seconds: 40.0
      size_mb: 3080
      architecture: "GPT-2"
    
    "gpt-neo-1.3B":
      energy_per_1k_wh: 8.8
      co2_per_1k_g: 4.4
      samples_per_second: 35
      duration_seconds: 28.6
      size_mb: 2500
      architecture: "GPT-Neo"
  
  # Text Classification Models
  text_classification:
    "distilbert-base-uncased":
      energy_per_1k_wh: 1.8
      co2_per_1k_g: 0.9
      samples_per_second: 150
      duration_seconds: 6.7
      size_mb: 67
      architecture: "BERT"
    
    "prajjwal1/bert-tiny":
      energy_per_1k_wh: 1.2
      co2_per_1k_g: 0.6
      samples_per_second: 200
      duration_seconds: 5.0
      size_mb: 17
      architecture: "BERT"
    
    "bert-base-uncased":
      energy_per_1k_wh: 4.2
      co2_per_1k_g: 2.1
      samples_per_second: 75
      duration_seconds: 13.3
      size_mb: 440
      architecture: "BERT"
  
  # Computer Vision Models
  computer_vision:
    # Salient Object Detection
    "BiRefNet":
      energy_per_1k_wh: 8.5
      co2_per_1k_g: 4.2
      samples_per_second: 12
      duration_seconds: 83.3
      size_mb: 45
      architecture: "CNN + Transformer hybrid"
    
    "U2Net":
      energy_per_1k_wh: 6.2
      co2_per_1k_g: 3.1
      samples_per_second: 18
      duration_seconds: 55.6
      size_mb: 176
      architecture: "U-Net based"
    
    "PoolNet":
      energy_per_1k_wh: 5.8
      co2_per_1k_g: 2.9
      samples_per_second: 22
      duration_seconds: 45.5
      size_mb: 68
      architecture: "PoolNet"
    
    # Object Detection
    "YOLOv8n":
      energy_per_1k_wh: 3.2
      co2_per_1k_g: 1.6
      samples_per_second: 45
      duration_seconds: 22.2
      size_mb: 6
      architecture: "YOLO"
    
    "YOLOv8s":
      energy_per_1k_wh: 4.1
      co2_per_1k_g: 2.0
      samples_per_second: 35
      duration_seconds: 28.6
      size_mb: 22
      architecture: "YOLO"
    
    "YOLOv8m":
      energy_per_1k_wh: 6.8
      co2_per_1k_g: 3.4
      samples_per_second: 25
      duration_seconds: 40.0
      size_mb: 50
      architecture: "YOLO"
    
    # Image Classification
    "ResNet-50":
      energy_per_1k_wh: 2.1
      co2_per_1k_g: 1.0
      samples_per_second: 120
      duration_seconds: 8.3
      size_mb: 98
      architecture: "ResNet"
    
    "EfficientNet-B0":
      energy_per_1k_wh: 1.8
      co2_per_1k_g: 0.9
      samples_per_second: 150
      duration_seconds: 6.7
      size_mb: 20
      architecture: "EfficientNet"
    
    "Vision Transformer (ViT-B/16)":
      energy_per_1k_wh: 4.5
      co2_per_1k_g: 2.2
      samples_per_second: 85
      duration_seconds: 11.8
      size_mb: 330
      architecture: "Transformer"

# =============================================================================
# HARDWARE CONFIGURATION
# =============================================================================
hardware:
  supported_types:
    "T4": "NVIDIA Tesla T4 16GB"
    "V100": "NVIDIA Tesla V100 32GB"
    "A100": "NVIDIA A100 40GB"
    "A100-80GB": "NVIDIA A100 80GB"
    "H100": "NVIDIA H100 80GB"
    "H100-SXM": "NVIDIA H100 SXM 80GB"
    "CPU": "CPU-only (no GPU)"
    "M1": "Apple M1 (development only)"
    "M2": "Apple M2 (development only)"
  
  # Device mapping for transformers library
  device_mapping:
    "CPU": -1  # CPU device for transformers
    "T4": 0    # First GPU
    "V100": 0
    "A100": 0
    "A100-80GB": 0
    "H100": 0
    "H100-SXM": 0
    "M1": -1   # CPU for Apple Silicon
    "M2": -1

# =============================================================================
# TASK CONFIGURATION
# =============================================================================
tasks:
  supported:
    - "text-classification"
    - "sentiment-analysis"
    - "image-classification"
    - "text-generation"
    - "question-answering"
    - "token-classification"
    - "summarization"
    - "translation"
    - "object_detection"
  
  # Task-specific settings
  settings:
    text_generation:
      max_length: 50
      do_sample: false
    
    image_classification:
      batch_size: 1
    
    object_detection:
      confidence_threshold: 0.5

# =============================================================================
# CODECARBON CONFIGURATION
# =============================================================================
codecarbon:
  # Power Usage Effectiveness (infrastructure overhead)
  pue: 1.2
  
  # Sampling frequency for power measurements (seconds)
  measure_power_secs: 1
  
  # Project naming pattern
  project_name_pattern: "{model_path}_{task}"

# =============================================================================
# MEASUREMENT CONFIGURATION
# =============================================================================
measurement:
  # Default sample sizes
  default_samples: 100
  default_samples_large: 1000
  
  # Default number of runs for reliability
  default_runs: 3
  
  # Progress reporting
  progress_interval_percent: 10  # Report every 10%
  progress_interval_samples: 100  # Or every 100 samples, whichever is smaller
  
  # Hardware detection timeout
  hardware_detection_timeout: 5  # seconds
  
  # Inference simulation delay (for testing)
  simulation_delay: 0.001  # seconds

# =============================================================================
# OUTPUT CONFIGURATION
# =============================================================================
output:
  # Default output directory
  default_dir: "results"
  
  # File naming patterns
  filename_pattern: "{model_name}_{timestamp}.json"
  timestamp_format: "%Y%m%d%H%M%S"
  
  # JSON formatting
  json_indent: 2
  
  # Directory structure: {output_dir}/{task}/{hardware}/
  use_task_hardware_structure: true

# =============================================================================
# LOGGING CONFIGURATION
# =============================================================================
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
  # Log file settings
  file_logging: false
  log_file: "energy_score.log"
  max_log_size: "10MB"
  backup_count: 5

# =============================================================================
# TESTING CONFIGURATION
# =============================================================================
testing:
  # Mock data settings
  mock_data:
    enable_variation: true
    variation_factor_range: [0.95, 1.05]  # ±5% variation
  
  # Test model specifications
  test_models:
    text_generation:
      - ["distilgpt2", "text_generation"]
      - ["gpt2", "text_generation"]
      - ["gpt2-medium", "text_generation"]
    
    computer_vision:
      - ["BiRefNet", "object_detection"]
      - ["U2Net", "object_detection"]
      - ["PoolNet", "object_detection"]
  
  # Test comparison weights
  test_weights:
    energy_focused:
      energy_efficiency: 0.6
      co2_efficiency: 0.4
      performance: 0.0
      speed: 0.0
    
    balanced:
      energy_efficiency: 0.4
      co2_efficiency: 0.3
      performance: 0.2
      speed: 0.1
